kind: Service
apiVersion: v1
metadata:
    name: tpi-hello-service
spec:
    type: LoadBalancer
    selector:
        app: tpi-hello
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080